In [20]:
import pandas as pd

df_batedores =  pd.read_csv("Dados_tratados_-_Batedores_2026.xlsx - GERAL.csv", usecols=[8, 97,98,100,101,102,103,104,105,106,109,110,111,112])
df_batedores.head(10)

,Unnamed: 8,Unnamed: 97,Unnamed: 98,19. Quem coleta o caroço de açaí?,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112
0,3. De quem você compra o fruto que você processa?,18. Onde você deposita os caroços de açaí temp...,18. Outro. Qual?,Serviço de limpeza pública,Coletor autônomo,Empresa privada,Outro,Não sabe,Não respondeu,19. Outro:,21. Qual recipiente você utiliza para armazena...,21. Outro. Qual?,22. Qual a quantidade média diária de caroço g...,23. Com que frequência os caroços de açaí são ...
1,Feiras/portos de açaí,"Na via pública (na calçada, na rua)",NaN,0,0,1,0,0,0,NaN,Outro,Saca de 100 kg,Até 1 unidade,Uma vez por semana
2,Atravessadores,"Na via pública (na calçada, na rua)",NaN,0,0,1,0,0,0,NaN,Bag de 1 tonelada,NaN,Até 1 unidade,Uma vez por semana
3,Extrativistas/famílias,Área privada para esse fim,NaN,0,0,1,0,0,0,NaN,Bag de 1 tonelada,NaN,Não sabe,Uma vez por semana
4,Extrativistas/famílias,"Na via pública (na calçada, na rua)",NaN,0,0,1,0,0,0,NaN,Bag de 1 tonelada,NaN,Até 1 unidade,Uma vez por semana
5,Atravessadores,Área privada para esse fim,NaN,0,0,0,0,0,1,NaN,Não respondeu,NaN,Não sabe,"Com frequência irregular, sem período definido"
6,Extrativistas/famílias,"Na via pública (na calçada, na rua)",NaN,0,0,1,0,0,0,NaN,Bag de 1 tonelada,NaN,Até 1 unidade,Uma vez por semana
7,Atravessadores,"Na via pública (na calçada, na rua)",NaN,0,0,1,0,0,0,NaN,Bag de 500 kg,NaN,Até 1 unidade,Uma vez por semana
8,Atravessadores,"Na via pública (na calçada, na rua)",NaN,0,0,1,0,0,0,NaN,Outro,Saca de 100 kg,Até 1 unidade,A cada 15 dias
9,Feiras/portos de açaí,"Na via pública (na calçada, na rua)",NaN,0,0,1,0,0,0,NaN,Outro,Saca de 100 kg,Até 1 unidade,"Com frequência irregular, sem período definido"

In [ ]:
df_coletores = pd.read_csv("Dados_tratados_-_Coletores_2026.xlsx - Geral.csv", usecols=[20,30,31,43,44,45,46])
df_coletores.head(10) ########

,4. Quais são os seus principais pontos de coleta?,6. Qual o destino do caroço de açaí que você coleta?,Questão 6 Outro,10. Qual medida que você utiliza para saber o volume de caroços de açaí coletados?,10. Outro,11. Qual o volume médio de caroços coletados durante um dia de trabalho?​,Questão 11 Quantas?
0,Batedores / Vitaminosas Cooperativa/associação,Entrega para empresa,NaN,Em toneladas,NaN,Médio (11-25 unidades),NaN
1,Batedores / Vitaminosas Via pública e entorno ...,Entrega para empresa,NaN,Outro,Saca de 100 kg,Médio (11-25 unidades),NaN
2,Batedores / Vitaminosas,Aproveito para adubo/compostagem,NaN,Em toneladas,NaN,Alto (26-50 unidades),NaN
3,Batedores / Vitaminosas,Entrega para empresa,NaN,Não respondeu,NaN,Alto (26-50 unidades),NaN
4,Batedores / Vitaminosas,Entrega para empresa,NaN,Não respondeu,NaN,Alto (26-50 unidades),NaN
5,Indústrias/ empresas,Entrega para empresa,NaN,Metros cúbicos (caçamba de caminhão),NaN,Alto (26-50 unidades),NaN
6,Batedores / Vitaminosas Indústrias/ empresas,Entrega para empresa,NaN,Em toneladas,NaN,Pequeno (até 10 unidades),NaN
7,Indústrias/ empresas,Entrega para empresa,NaN,Em toneladas,NaN,Médio (11-25 unidades),NaN
8,Batedores / Vitaminosas Via pública e entorno ...,Outro. Qual?,Entrega para empresa de reciclagem,Metros cúbicos (caçamba de caminhão),NaN,Caçamba de caminhão. Quantas,De 5 a 8 unidades
9,Indústrias/ empresas Batedores / Vitaminosas,Entrega para empresa,NaN,Em toneladas,NaN,Muito alto (mais de 50 unidades),NaN